### ISSUE TITLE
no "interim" result when stateLoading is false

### ISSUE THREAD

**Issue by MrTelanie** [misantronic/wrap-request#25]
i am not sure, if its possible to write a unit test for that situation, i try to describe it with words. :)

i have the situation all data is there and loaded.
now i get pings from backend to fetch new data, in that case i make same request with `stateLoading: false`. normally this works fine, nut in my case i get the next ping before last request is handled.

this leads to case, that data is first refreshed, when last request is finished.
but frontend could show that valid "interim" result.

----

i think the solution would be a smarter handling of `this.xhrVersion`, there should be a `resultVersion`, but not sure :)

**Comment by misantronic** [comment]
at the moment, we make a hard comparison 

```js
if (this.xhrVersion === version) { ... }
```

we might disable this via parameter.
but what happens when the lastest request finishes before the older ones? we should always make sure that the latest request wins in the end.

**Comment by MrTelanie** [comment]
i think i have a workaround:
```
 private checkXhrVersion(version: number, stateLoading?: boolean): boolean {
        if (stateLoading) {
            return  this.xhrVersion === version;
        }
        return this.xhrVersion >= version;
    }
```

**Comment by MrTelanie** [comment]
now i could create i working PR
https://github.com/misantronic/wrap-request/pull/27
